"""
dashboard.py — Ticker-Teller NIFTY 100 Prediction Dashboard
============================================================
Reads Excel workbooks generated by nifty100_tracker.py and renders
an interactive Streamlit analytics dashboard.

Usage:
    streamlit run dashboard.py

    # Custom workbooks directory:
    streamlit run dashboard.py -- --workbooks /path/to/workbooks

Requirements:
    pip install streamlit plotly openpyxl pandas
"""

from __future__ import annotations

import argparse
import sys
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from openpyxl import load_workbook

# ── Page config (must be the very first Streamlit call) ───────────────────────
st.set_page_config(
    page_title  = "Ticker-Teller Dashboard",
    page_icon   = "📈",
    layout      = "wide",
    initial_sidebar_state = "expanded",
)

# ═══════════════════════════════════════════════════════════════════════════════
# CSS — dark finance theme (consistent with Ticker-Teller Streamlit app)
# ═══════════════════════════════════════════════════════════════════════════════

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Syne:wght@400;600;700;800&family=Inter:wght@300;400;500;600&display=swap');

/* ── Base ── */
.stApp, .block-container { background-color: #080f1c !important; }
section[data-testid="stSidebar"] { background-color: #040a13 !important; border-right: 1px solid #1a2f4a; }
html, body, [class*="css"], p, span, div, label { font-family: 'Inter', sans-serif; color: #e2e8f0; }

/* ── Hero banner ── */
.tt-hero {
    background: linear-gradient(135deg, #0d1b2e 0%, #0a1929 40%, #0d2137 100%);
    border: 1px solid #1a3557;
    border-radius: 20px;
    padding: 2.2rem 2.8rem 1.8rem;
    margin-bottom: 1.8rem;
    position: relative;
    overflow: hidden;
}
.tt-hero::before {
    content: '';
    position: absolute;
    top: -60px; right: -60px;
    width: 220px; height: 220px;
    background: radial-gradient(circle, rgba(56,189,248,0.08) 0%, transparent 70%);
    border-radius: 50%;
}
.tt-hero-title {
    font-family: 'Syne', sans-serif;
    font-size: 2.4rem;
    font-weight: 800;
    background: linear-gradient(90deg, #38bdf8 0%, #818cf8 50%, #e879f9 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    margin: 0 0 0.3rem 0;
    letter-spacing: -0.5px;
}
.tt-hero-sub {
    font-family: 'DM Mono', monospace;
    color: #64748b;
    font-size: 0.76rem;
    letter-spacing: 0.1em;
    text-transform: uppercase;
}

/* ── Section headers ── */
.sec-hdr {
    font-family: 'Syne', sans-serif;
    font-size: 1.05rem;
    font-weight: 700;
    color: #f1f5f9;
    border-left: 3px solid #38bdf8;
    padding-left: 0.75rem;
    margin: 1.6rem 0 1rem 0;
}

/* ── KPI cards ── */
[data-testid="metric-container"] {
    background: #0d1b2e !important;
    border: 1px solid #1a3557 !important;
    border-radius: 14px !important;
    padding: 1.1rem 1.3rem !important;
}
[data-testid="stMetricLabel"] > div,
[data-testid="stMetricLabel"] p {
    font-family: 'DM Mono', monospace !important;
    font-size: 0.65rem !important;
    color: #64748b !important;
    letter-spacing: 0.1em !important;
    text-transform: uppercase !important;
}
[data-testid="stMetricValue"] > div,
[data-testid="stMetricValue"] p {
    font-family: 'Syne', sans-serif !important;
    font-size: 1.65rem !important;
    font-weight: 700 !important;
    color: #f8fafc !important;
}

/* ── Sidebar ── */
.sidebar-label {
    font-family: 'DM Mono', monospace;
    font-size: 0.62rem;
    color: #38bdf8;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 0.25rem;
}
[data-testid="stSelectbox"] > div > div {
    background: #0d1b2e !important;
    border: 1px solid #1a3557 !important;
    border-radius: 8px !important;
    color: #f1f5f9 !important;
}

/* ── Tabs ── */
[data-testid="stTabs"] [role="tab"] {
    font-family: 'DM Mono', monospace !important;
    font-size: 0.76rem !important;
    color: #64748b !important;
    letter-spacing: 0.06em !important;
}
[data-testid="stTabs"] [role="tab"][aria-selected="true"] {
    color: #38bdf8 !important;
    border-bottom-color: #38bdf8 !important;
}

/* ── Data table ── */
[data-testid="stDataFrame"] { border-radius: 10px; overflow: hidden; }
[data-testid="stDataFrame"] table { background: #0d1b2e !important; }
[data-testid="stDataFrame"] th {
    background: #1a3557 !important;
    color: #94a3b8 !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 0.7rem !important;
}
[data-testid="stDataFrame"] td {
    background: #0d1b2e !important;
    color: #e2e8f0 !important;
    font-size: 0.78rem !important;
}

/* ── Info / warning boxes ── */
[data-testid="stAlert"] { border-radius: 10px !important; }

/* ── Slider ── */
[data-testid="stSlider"] > div > div > div { background: #1a3557 !important; }

/* ── Misc ── */
hr { border-color: #1a3557 !important; }
[data-testid="stCaptionContainer"] p {
    color: #475569 !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 0.7rem !important;
}
</style>
""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

# Excel column indices (1-based, matching tracker layout)
_COL_DATE     = 1   # A
_COL_TICKER   = 2   # B
_COL_PRICE_F  = 3   # C  — price branch features (long text)
_COL_FACTOR_F = 4   # D  — quant factor features (long text)
_COL_ACTUAL   = 5   # E
_COL_PRED     = 6   # F
_COL_ERROR    = 7   # G
_COL_SIGNED   = 8   # H  (hidden signed error — skipped)
_DATA_START   = 3   # first data row (rows 1-2 are merged headers)

# Plotly dark theme shared across all charts
_LAYOUT_BASE = dict(
    template      = "plotly_dark",
    paper_bgcolor = "#080f1c",
    plot_bgcolor  = "#080f1c",
    hovermode     = "x unified",
    hoverlabel    = dict(
        bgcolor     = "#0d1b2e",
        bordercolor = "#1a3557",
        font        = dict(family="DM Mono, monospace", color="#e2e8f0", size=12),
    ),
    font          = dict(family="DM Mono, monospace", color="#e2e8f0", size=12),
    legend        = dict(
        bgcolor     = "#0d1b2e",
        bordercolor = "#1a3557",
        borderwidth = 1,
        font        = dict(family="DM Mono", color="#e2e8f0", size=11),
    ),
    margin        = dict(l=20, r=20, t=50, b=20),
)
_AXIS_STYLE = dict(
    gridcolor     = "#1a3557",
    zerolinecolor = "#1a3557",
    tickfont      = dict(color="#94a3b8", family="DM Mono, monospace", size=11),
)

# ═══════════════════════════════════════════════════════════════════════════════
# WORKBOOK DIRECTORY — resolve at startup
# ═══════════════════════════════════════════════════════════════════════════════

def _resolve_workbook_dir() -> Path:
    """
    Priority:
      1. CLI arg  --workbooks <path>
      2. Streamlit query param  ?workbooks=<path>
      3. workbooks/ sibling of this script
    """
    # CLI args passed after  `streamlit run dashboard.py --`
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--workbooks", default=None)
    known, _ = parser.parse_known_args()
    if known.workbooks:
        return Path(known.workbooks)

    params = st.query_params
    if "workbooks" in params:
        return Path(params["workbooks"])

    return Path(__file__).parent / "workbooks"


WORKBOOK_DIR = _resolve_workbook_dir()

# ═══════════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═══════════════════════════════════════════════════════════════════════════════

@st.cache_data(show_spinner=False)
def discover_workbooks(directory: str) -> dict[str, Path]:
    """
    Scan the workbooks directory and return {ticker_display_name: Path}.
    Filename format: RELIANCE_NS.xlsx → RELIANCE.NS
    """
    d = Path(directory)
    if not d.exists():
        return {}

    result = {}
    for f in sorted(d.glob("*.xlsx")):
        # Read the actual ticker symbol from col B row 3 — ground truth.
        ticker = _peek_ticker(f) or _ticker_from_stem(f.stem)
        result[ticker] = f
    return result


def _ticker_from_stem(stem: str) -> str:
    """Fallback: reverse the safe-filename transform on the workbook stem."""
    stem = stem.replace("AND", "&")
    parts = stem.rsplit("_", 1)
    if len(parts) == 2 and parts[1] in ("NS", "BO"):
        return f"{parts[0]}.{parts[1]}"
    return stem.replace("_", ".")


def _peek_ticker(path: Path) -> str | None:
    """Read the Ticker value from the first data row (col B, row 3)."""
    try:
        wb = load_workbook(str(path), data_only=True, read_only=True)
        if "Predictions" not in wb.sheetnames:
            wb.close()
            return None
        ws = wb["Predictions"]
        for row in ws.iter_rows(min_row=_DATA_START, max_row=_DATA_START + 5,
                                values_only=True):
            val = row[_COL_TICKER - 1]
            if val and str(val).strip():
                wb.close()
                return str(val).strip()
        wb.close()
    except Exception:
        pass
    return None


@st.cache_data(show_spinner=False)
def load_workbook_data(filepath: str) -> pd.DataFrame:
    """
    Read the Predictions sheet from one tracker workbook.
    Returns a clean DataFrame with columns:
        Date, Ticker, Actual, Predicted, Error_pct, Price_Features, Factor_Features
    Skips the two merged header rows and any rows that can't be parsed.
    """
    wb = load_workbook(filepath, data_only=True, read_only=True)

    if "Predictions" not in wb.sheetnames:
        wb.close()
        return pd.DataFrame()

    ws = wb["Predictions"]
    rows = []

    for row_idx, row in enumerate(ws.iter_rows(min_row=_DATA_START, values_only=True), start=_DATA_START):
        # row is a tuple indexed 0-based; col indices are 1-based in tracker
        try:
            date_val      = row[_COL_DATE     - 1]
            ticker_val    = row[_COL_TICKER   - 1]
            price_f_val   = row[_COL_PRICE_F  - 1]
            factor_f_val  = row[_COL_FACTOR_F - 1]
            actual_val    = row[_COL_ACTUAL   - 1]
            pred_val      = row[_COL_PRED     - 1]
            error_val     = row[_COL_ERROR    - 1]

            # Skip completely empty rows
            if all(v is None for v in (date_val, actual_val, pred_val)):
                continue

            # Parse date
            if isinstance(date_val, str):
                try:
                    date_val = pd.to_datetime(date_val).date()
                except Exception:
                    continue
            elif hasattr(date_val, "date"):
                date_val = date_val.date()
            elif date_val is None:
                continue

            # Coerce numerics
            actual_val = _safe_float(actual_val)
            pred_val   = _safe_float(pred_val)

            if actual_val is None or pred_val is None:
                continue

            # Recompute error from raw values — don't trust cached formula result
            error_pct = abs((actual_val - pred_val) / actual_val * 100) if actual_val != 0 else None
            signed_err = ((actual_val - pred_val) / actual_val * 100) if actual_val != 0 else 0

            rows.append({
                "Date"            : date_val,
                "Ticker"          : str(ticker_val) if ticker_val else "",
                "Actual"          : actual_val,
                "Predicted"       : pred_val,
                "Error_pct"       : error_pct,
                "Signed_Error"    : signed_err,
                "Price_Features"  : str(price_f_val)  if price_f_val  else "",
                "Factor_Features" : str(factor_f_val) if factor_f_val else "",
            })
        except (IndexError, TypeError):
            continue

    wb.close()

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows)
    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values("Date").reset_index(drop=True)
    return df


def _safe_float(val) -> float | None:
    if val is None:
        return None
    try:
        f = float(val)
        return None if (np.isnan(f) or np.isinf(f)) else f
    except (TypeError, ValueError):
        return None


# ═══════════════════════════════════════════════════════════════════════════════
# CHART BUILDERS
# ═══════════════════════════════════════════════════════════════════════════════

def build_price_chart(df: pd.DataFrame, ticker: str) -> go.Figure:
    """Actual vs Predicted price overlay with gap shading."""
    fig = go.Figure()

    # Confidence gap fill (between actual and predicted)
    fig.add_trace(go.Scatter(
        x    = pd.concat([df["Date"], df["Date"][::-1]]),
        y    = pd.concat([df["Actual"], df["Predicted"][::-1]]),
        fill = "toself",
        fillcolor = "rgba(56,189,248,0.06)",
        line = dict(color="rgba(0,0,0,0)"),
        hoverinfo = "skip",
        showlegend= False,
        name = "Gap",
    ))

    # Actual price
    fig.add_trace(go.Scatter(
        x          = df["Date"],
        y          = df["Actual"],
        mode       = "lines+markers",
        name       = "Actual Price",
        line       = dict(color="#38bdf8", width=2.5),
        marker     = dict(size=5, color="#38bdf8",
                          line=dict(color="#080f1c", width=1)),
        hovertemplate = "<b>Actual</b>: ₹%{y:,.2f}<extra></extra>",
    ))

    # Predicted price
    fig.add_trace(go.Scatter(
        x          = df["Date"],
        y          = df["Predicted"],
        mode       = "lines+markers",
        name       = "Predicted Price",
        line       = dict(color="#f472b6", width=2, dash="dash"),
        marker     = dict(size=5, color="#f472b6",
                          line=dict(color="#080f1c", width=1)),
        hovertemplate = "<b>Predicted</b>: ₹%{y:,.2f}<extra></extra>",
    ))

    fig.update_layout(
        title = dict(
            text      = f"<b>{ticker}</b>  —  Actual vs Predicted Price",
            font      = dict(family="Syne, sans-serif", size=16, color="#f1f5f9"),
            x         = 0.01,
        ),
        height     = 420,
        xaxis      = dict(title="Date", tickformat="%b %d, %Y", **_AXIS_STYLE),
        yaxis      = dict(title="Price (₹)", **_AXIS_STYLE),
        **_LAYOUT_BASE,
    )
    return fig


def build_error_chart(df: pd.DataFrame, ticker: str) -> go.Figure:
    """Daily absolute error % as a bar chart with signed colour coding."""
    colours = [
        "#4ade80" if s >= 0 else "#f87171"
        for s in df["Signed_Error"]
    ]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x             = df["Date"],
        y             = df["Error_pct"],
        marker_color  = colours,
        marker_line   = dict(color="rgba(0,0,0,0)", width=0),
        name          = "Error (%)",
        hovertemplate = "<b>Error</b>: %{y:.2f}%<extra></extra>",
        opacity       = 0.85,
    ))

    # Average error line
    avg_err = df["Error_pct"].mean()
    fig.add_hline(
        y                    = avg_err,
        line_dash            = "dot",
        line_color           = "rgba(251,191,36,0.7)",
        annotation_text      = f" Avg {avg_err:.2f}%",
        annotation_font      = dict(color="#fbbf24", size=11),
        annotation_position  = "top right",
    )

    fig.update_layout(
        title = dict(
            text  = f"<b>{ticker}</b>  —  Prediction Error (%) per Day",
            font  = dict(family="Syne, sans-serif", size=16, color="#f1f5f9"),
            x     = 0.01,
        ),
        height = 320,
        xaxis  = dict(title="Date", tickformat="%b %d, %Y", **_AXIS_STYLE),
        yaxis  = dict(title="Absolute Error (%)", **_AXIS_STYLE),
        **_LAYOUT_BASE,
    )
    return fig


def build_scatter_chart(df: pd.DataFrame, ticker: str) -> go.Figure:
    """Actual vs Predicted scatter — perfect prediction = diagonal."""
    lo = min(df["Actual"].min(), df["Predicted"].min()) * 0.995
    hi = max(df["Actual"].max(), df["Predicted"].max()) * 1.005

    colours = [
        "#4ade80" if s >= 0 else "#f87171"
        for s in df["Signed_Error"]
    ]

    fig = go.Figure()

    # Perfect prediction diagonal
    fig.add_trace(go.Scatter(
        x         = [lo, hi],
        y         = [lo, hi],
        mode      = "lines",
        name      = "Perfect Prediction",
        line      = dict(color="rgba(148,163,184,0.35)", width=1.5, dash="dot"),
        hoverinfo = "skip",
    ))

    fig.add_trace(go.Scatter(
        x             = df["Actual"],
        y             = df["Predicted"],
        mode          = "markers",
        name          = "Predictions",
        marker        = dict(
            size   = 8,
            color  = colours,
            opacity= 0.85,
            line   = dict(color="#080f1c", width=0.8),
        ),
        customdata    = df["Date"].dt.strftime("%Y-%m-%d"),
        hovertemplate = (
            "<b>%{customdata}</b><br>"
            "Actual: ₹%{x:,.2f}<br>"
            "Predicted: ₹%{y:,.2f}<extra></extra>"
        ),
    ))

    fig.update_layout(
        title  = dict(
            text = f"<b>{ticker}</b>  —  Actual vs Predicted Scatter",
            font = dict(family="Syne, sans-serif", size=16, color="#f1f5f9"),
            x    = 0.01,
        ),
        height = 380,
        xaxis  = dict(title="Actual Price (₹)", range=[lo, hi], **_AXIS_STYLE),
        yaxis  = dict(title="Predicted Price (₹)", range=[lo, hi], **_AXIS_STYLE),
        **_LAYOUT_BASE,
    )
    return fig


def build_cumulative_return_chart(df: pd.DataFrame, ticker: str) -> go.Figure:
    """Cumulative return: actual vs predicted, base = first day."""
    if len(df) < 2:
        return go.Figure()

    base_a = df["Actual"].iloc[0]
    base_p = df["Predicted"].iloc[0]
    cum_actual    = (df["Actual"]    / base_a - 1) * 100
    cum_predicted = (df["Predicted"] / base_p - 1) * 100

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x             = df["Date"],
        y             = cum_actual,
        mode          = "lines",
        name          = "Actual Return",
        line          = dict(color="#38bdf8", width=2.5),
        hovertemplate = "<b>Actual</b>: %{y:.2f}%<extra></extra>",
    ))
    fig.add_trace(go.Scatter(
        x             = df["Date"],
        y             = cum_predicted,
        mode          = "lines",
        name          = "Predicted Return",
        line          = dict(color="#818cf8", width=2, dash="dash"),
        hovertemplate = "<b>Predicted</b>: %{y:.2f}%<extra></extra>",
    ))
    fig.add_hline(y=0, line_color="rgba(148,163,184,0.25)", line_dash="solid")

    fig.update_layout(
        title  = dict(
            text = f"<b>{ticker}</b>  —  Cumulative Return (%)",
            font = dict(family="Syne, sans-serif", size=16, color="#f1f5f9"),
            x    = 0.01,
        ),
        height = 350,
        xaxis  = dict(title="Date", tickformat="%b %d, %Y", **_AXIS_STYLE),
        yaxis  = dict(title="Cumulative Return (%)", **_AXIS_STYLE),
        **_LAYOUT_BASE,
    )
    return fig


# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY STATISTICS
# ═══════════════════════════════════════════════════════════════════════════════

def compute_stats(df: pd.DataFrame) -> dict:
    errors = df["Error_pct"].dropna()
    signed = df["Signed_Error"].dropna()

    correct_direction = (signed > 0).sum()
    dir_acc = correct_direction / len(signed) * 100 if len(signed) > 0 else 0

    price_change_pct = (
        (df["Actual"].iloc[-1] - df["Actual"].iloc[0]) / df["Actual"].iloc[0] * 100
        if len(df) > 1 else 0
    )

    return {
        "days"          : len(df),
        "avg_error"     : errors.mean(),
        "median_error"  : errors.median(),
        "max_error"     : errors.max(),
        "min_error"     : errors.min(),
        "std_error"     : errors.std(),
        "dir_accuracy"  : dir_acc,
        "total_return"  : price_change_pct,
        "last_actual"   : df["Actual"].iloc[-1],
        "last_predicted": df["Predicted"].iloc[-1],
    }


# ═══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ═══════════════════════════════════════════════════════════════════════════════

def render_sidebar(workbooks: dict[str, Path]) -> tuple[str | None, pd.DataFrame | None]:
    """Render sidebar controls. Returns (selected_ticker, filtered_df)."""

    with st.sidebar:
        st.markdown("""
<div style="padding:1.2rem 0 1rem">
  <div style="font-family:'Syne',sans-serif;font-size:1.4rem;font-weight:800;
              background:linear-gradient(90deg,#38bdf8,#818cf8);
              -webkit-background-clip:text;-webkit-text-fill-color:transparent;
              background-clip:text">
    📈 Ticker-Teller
  </div>
  <div style="font-family:'DM Mono',monospace;font-size:0.62rem;
              color:#475569;letter-spacing:0.1em;margin-top:0.2rem">
    NIFTY 100  ·  PREDICTION DASHBOARD
  </div>
</div>
""", unsafe_allow_html=True)

        st.divider()

        if not workbooks:
            st.error(f"No workbooks found in:\n`{WORKBOOK_DIR}`\n\nRun the tracker first.")
            return None, None

        # ── Ticker selector ────────────────────────────────────────────────────
        st.markdown('<div class="sidebar-label">Select Company</div>',
                    unsafe_allow_html=True)
        tickers = sorted(workbooks.keys())
        selected = st.selectbox("", tickers, label_visibility="collapsed",
                                key="ticker_select")

        # ── Load data ─────────────────────────────────────────────────────────
        df_full = load_workbook_data(str(workbooks[selected]))

        if df_full.empty:
            st.warning("No data rows found in this workbook.")
            return selected, None

        # ── Date range filter ──────────────────────────────────────────────────
        st.markdown('<div class="sidebar-label" style="margin-top:1.2rem">Date Range</div>',
                    unsafe_allow_html=True)

        min_date = df_full["Date"].min().date()
        max_date = df_full["Date"].max().date()

        date_from = st.date_input("From", value=min_date,
                                  min_value=min_date, max_value=max_date,
                                  key="date_from", label_visibility="collapsed")
        date_to   = st.date_input("To",   value=max_date,
                                  min_value=min_date, max_value=max_date,
                                  key="date_to",   label_visibility="collapsed")

        if date_from > date_to:
            st.warning("'From' date is after 'To' date — swapping.")
            date_from, date_to = date_to, date_from

        df = df_full[
            (df_full["Date"].dt.date >= date_from) &
            (df_full["Date"].dt.date <= date_to)
        ].reset_index(drop=True)

        st.divider()

        # ── Workbook info ──────────────────────────────────────────────────────
        st.markdown(f"""
<div style="font-family:'DM Mono',monospace;font-size:0.68rem;
            line-height:2;color:#475569">
  <span style="color:#38bdf8">●</span>  {len(df_full)} total rows<br>
  <span style="color:#818cf8">●</span>  {len(df)} after filter<br>
  <span style="color:#4ade80">●</span>  {min_date}  →  {max_date}
</div>
""", unsafe_allow_html=True)

        return selected, df


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN APP
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:

    # ── Hero banner ────────────────────────────────────────────────────────────
    st.markdown("""
<div class="tt-hero">
  <div class="tt-hero-title">📈 Ticker-Teller Dashboard</div>
  <div class="tt-hero-sub">
    NIFTY 100  ·  CNN → BILSTM → ATTENTION  ·  MONTE CARLO UNCERTAINTY ESTIMATION
  </div>
</div>
""", unsafe_allow_html=True)

    # ── Discover workbooks ─────────────────────────────────────────────────────
    workbooks = discover_workbooks(str(WORKBOOK_DIR))

    # ── Sidebar ────────────────────────────────────────────────────────────────
    ticker, df = render_sidebar(workbooks)

    if ticker is None:
        st.info(
            f"📂  Workbooks directory: **`{WORKBOOK_DIR}`**\n\n"
            "Run `python3 nifty100_tracker.py --once` to generate prediction data, "
            "then refresh this page."
        )
        return

    if df is None or df.empty:
        st.warning(
            f"No data available for **{ticker}** in the selected date range. "
            "Try widening the date filter."
        )
        return

    stats = compute_stats(df)

    # ── KPI row ────────────────────────────────────────────────────────────────
    st.markdown('<div class="sec-hdr">📊 Summary Statistics</div>',
                unsafe_allow_html=True)

    k1, k2, k3, k4, k5, k6 = st.columns(6)
    k1.metric("LAST ACTUAL PRICE",     f"₹{stats['last_actual']:,.2f}")
    k2.metric("LAST PREDICTED PRICE",  f"₹{stats['last_predicted']:,.2f}")
    k3.metric("AVG ERROR (%)",          f"{stats['avg_error']:.2f}%")
    k4.metric("MEDIAN ERROR (%)",       f"{stats['median_error']:.2f}%")
    k5.metric("DIRECTIONAL ACCURACY",  f"{stats['dir_accuracy']:.1f}%")
    k6.metric("TOTAL RETURN (ACTUAL)",
              f"{stats['total_return']:+.2f}%",
              delta=f"{stats['total_return']:+.2f}%")

    # ── Error stats row ────────────────────────────────────────────────────────
    e1, e2, e3, e4 = st.columns(4)
    e1.metric("MAX ERROR (%)",    f"{stats['max_error']:.2f}%")
    e2.metric("MIN ERROR (%)",    f"{stats['min_error']:.2f}%")
    e3.metric("STD DEV ERROR",    f"{stats['std_error']:.2f}%")
    e4.metric("DAYS ANALYSED",    str(stats["days"]))

    # ── Main chart tabs ────────────────────────────────────────────────────────
    st.markdown('<div class="sec-hdr">📈 Charts</div>', unsafe_allow_html=True)

    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "📉  PRICE",
        "❌  ERROR",
        "🔵  SCATTER",
        "📈  CUMULATIVE RETURN",
        "🗂️  DATA TABLE",
    ])

    with tab1:
        st.plotly_chart(
            build_price_chart(df, ticker),
            use_container_width=True,
        )
        st.caption(
            f"Blue = Actual closing price  ·  Pink dashed = Model predicted price  ·  "
            f"{stats['days']} trading days shown"
        )

    with tab2:
        st.plotly_chart(
            build_error_chart(df, ticker),
            use_container_width=True,
        )
        st.caption(
            "🟢 Green bar = model underestimated (Actual > Predicted)  ·  "
            "🔴 Red bar = model overestimated (Actual < Predicted)  ·  "
            "Yellow dot line = average error"
        )

    with tab3:
        st.plotly_chart(
            build_scatter_chart(df, ticker),
            use_container_width=True,
        )
        st.caption(
            "Points on the diagonal = perfect predictions.  "
            "🟢 Green = model underestimated  ·  🔴 Red = model overestimated"
        )

    with tab4:
        if stats["days"] >= 2:
            st.plotly_chart(
                build_cumulative_return_chart(df, ticker),
                use_container_width=True,
            )
            st.caption(
                "Cumulative % return from the first day in the selected range.  "
                "Blue = actual price path  ·  Purple dashed = predicted price path."
            )
        else:
            st.info("Need at least 2 data points to compute cumulative return.")

    with tab5:
        st.markdown(
            '<div class="sec-hdr" style="margin-top:0.5rem">Raw Prediction Data</div>',
            unsafe_allow_html=True,
        )

        # Build display table (hide long feature text by default)
        show_features = st.checkbox("Show model feature columns (verbose)", value=False)

        display_cols = ["Date", "Ticker", "Actual", "Predicted", "Error_pct", "Signed_Error"]
        if show_features:
            display_cols += ["Price_Features", "Factor_Features"]

        df_display = df[display_cols].copy()
        df_display["Date"]       = df_display["Date"].dt.strftime("%Y-%m-%d")
        df_display["Actual"]     = df_display["Actual"].map("₹{:,.2f}".format)
        df_display["Predicted"]  = df_display["Predicted"].map("₹{:,.2f}".format)
        df_display["Error_pct"]  = df_display["Error_pct"].map("{:.2f}%".format)
        df_display["Signed_Error"] = df_display["Signed_Error"].map("{:+.2f}%".format)

        df_display.columns = (
            ["Date", "Ticker", "Actual Price", "Predicted Price",
             "Error (%)", "Signed Error (%)"]
            + (["Price Features", "Factor Features"] if show_features else [])
        )

        st.dataframe(df_display, use_container_width=True, hide_index=True)

        # CSV download
        csv = df[display_cols].to_csv(index=False).encode("utf-8")
        st.download_button(
            label    = "⬇️  Download as CSV",
            data     = csv,
            file_name= f"{ticker.replace('.', '_')}_predictions.csv",
            mime     = "text/csv",
        )

    # ── Multi-ticker comparison (bonus) ───────────────────────────────────────
    st.markdown('<div class="sec-hdr">🔁 Compare Multiple Tickers</div>',
                unsafe_allow_html=True)
    st.caption(
        "Select additional tickers to overlay their actual prices on one chart."
    )

    all_tickers = sorted(workbooks.keys())
    compare_tickers = st.multiselect(
        "Add tickers to compare",
        options  = [t for t in all_tickers if t != ticker],
        default  = [],
        key      = "compare_select",
        label_visibility = "collapsed",
    )

    if compare_tickers:
        fig_cmp = go.Figure()

        # Include the primary ticker first
        for t in [ticker] + compare_tickers:
            df_t = load_workbook_data(str(workbooks[t]))
            if df_t.empty:
                continue
            fig_cmp.add_trace(go.Scatter(
                x             = df_t["Date"],
                y             = df_t["Actual"],
                mode          = "lines",
                name          = t,
                hovertemplate = f"<b>{t}</b>: ₹%{{y:,.2f}}<extra></extra>",
            ))

        fig_cmp.update_layout(
            title  = dict(
                text = "Actual Price Comparison",
                font = dict(family="Syne, sans-serif", size=16, color="#f1f5f9"),
                x    = 0.01,
            ),
            height = 380,
            xaxis  = dict(title="Date", tickformat="%b %d, %Y", **_AXIS_STYLE),
            yaxis  = dict(title="Price (₹)", **_AXIS_STYLE),
            **_LAYOUT_BASE,
        )
        st.plotly_chart(fig_cmp, use_container_width=True)

    # ── Footer ─────────────────────────────────────────────────────────────────
    st.divider()
    st.markdown("""
<div style="text-align:center;font-family:'DM Mono',monospace;
            font-size:0.65rem;color:#334155;padding:0.5rem 0 1rem">
  Ticker-Teller  ·  CNN → BiLSTM → Attention  ×  Monte Carlo  ·  NSE NIFTY 100<br>
  For educational and research use only. Not financial advice.
</div>
""", unsafe_allow_html=True)


if __name__ == "__main__":
    main()
